from Testing.progress_tracker import ProgressTracker
from Testing.utils import (
    open_json,
    run_tests,
    EXPECTED_OUTPUT_FOLDER_NAME,
)
from Parsing.expression_parsing import parse_expression

ERRORS_SAMPLE_INPUT_FOLDER_NAME = "ExpressionErrorTestCases"
MANUAL_SAMPLE_INPUT_FOLDER_NAME = "ManualInputs"
MANUAL_BOOLEAN_SAMPLE_INPUT_FOLDER_NAME = "InputFiles"
AUTO_GENERATED_SAMPLE_INPUT_FOLDER_NAME = "InputFiles"

def run_expression_parser_tests(progress_tracker: ProgressTracker) -> None:
    part_one(progress_tracker)
    part_two(progress_tracker)
    manual_tests(progress_tracker)
    manual_boolean_tests(progress_tracker)
    auto_generated_test_cases(progress_tracker)


def part_one(progress_tracker: ProgressTracker) -> None:
    error_tests = open_json(
        "Testing/Parsing/ExpressionParsing/expparser_error_tests.json"
    )
    test_case_folder = "Testing/Parsing/ExpressionParsing/part_1"
    print("Running expression error tests")
    run_tests(
        error_tests, test_case_folder, ERRORS_SAMPLE_INPUT_FOLDER_NAME, EXPECTED_OUTPUT_FOLDER_NAME, progress_tracker, parse_expression
    )


def part_two(progress_tracker: ProgressTracker) -> None:
    error_tests = open_json(
        "Testing/Parsing/ExpressionParsing/expparser_error_tests_pt_2.json"
    )
    test_case_folder = "Testing/Parsing/ExpressionParsing/part_2"
    print("Running expression error tests, part 2")
    run_tests(
        error_tests, test_case_folder, ERRORS_SAMPLE_INPUT_FOLDER_NAME, EXPECTED_OUTPUT_FOLDER_NAME, progress_tracker, parse_expression
    )


def manual_tests(progress_tracker: ProgressTracker) -> None:
    error_tests = open_json(
        "Testing/Parsing/ExpressionParsing/expparser_manual_tests.json"
    )
    test_case_folder = "Testing/Parsing/ExpressionParsing/ManualTests"
    print("Running expression manual tests")
    run_tests(
        error_tests, test_case_folder, MANUAL_SAMPLE_INPUT_FOLDER_NAME, EXPECTED_OUTPUT_FOLDER_NAME, progress_tracker, parse_expression
    )


def manual_boolean_tests(progress_tracker: ProgressTracker) -> None:
    error_tests = open_json(
        "Testing/Parsing/ExpressionParsing/expparser_manual_boolean_tests.json"
    )
    test_case_folder = "Testing/Parsing/ExpressionParsing/ManualBooleanTests"
    print("Running expression boolean tests")
    run_tests(
        error_tests, test_case_folder, MANUAL_BOOLEAN_SAMPLE_INPUT_FOLDER_NAME, EXPECTED_OUTPUT_FOLDER_NAME, progress_tracker, parse_expression
    )


def auto_generated_test_cases(progress_tracker: ProgressTracker) -> None:
    error_tests = open_json(
        "Testing/Parsing/ExpressionParsing/expparser_auto_tests.json"
    )
    test_case_folder = "Testing/Parsing/ExpressionParsing/AutoGeneratedTests"
    print("Running expression auto generated tests")
    run_tests(
        error_tests, test_case_folder, AUTO_GENERATED_SAMPLE_INPUT_FOLDER_NAME, EXPECTED_OUTPUT_FOLDER_NAME, progress_tracker, parse_expression
    )
