# Autogenerated code from Autopilot Compiler
# Autopilot Programming Language made by Mark Tigchelaar
from __future__ import annotations # For delayed type evaluation, to define classes, enums etc. after type defines


string = str
char = str
true = True
false = False
long = int
double = float



def main_main() -> None:
    a: int = 2
    b: int = 3
    c: int = (a ** b)
    if ((a < b) and (b < c)):
        d: int = (c - 1)
        print(d)
    else:
        d: int = (c + 1)





if __name__ == '__main__':
    main_main()
