module TypeDefIds
    ENUM = 0
    UNION = 1
    CODEBLOCK = 2
    FUNCTION = 3
    FUNCTION_SIGNATURE = 4
    STRUCT = 5
    MODULE = 6
    IMPORT_LIBRARY = 7
    DEFINE = 8
    INTERFACE = 9
    FUNCTION_ARGUMENT = 10
    FUNCTION_CALL_ARGUMENT = 11
    LOCAL_VARIABLE = 12
    VALUE_FIELD = 13
    REFERENCE_FIELD = 14
    RETURN_VALUE = 15
    ENUM_TYPE = 16
    FUNCTION_CALL = 17
    IMPORT_MODULE = 18
end