require './tokentype.rb'


def getkeywords
    keywords = {
        "module" => MODULE,
        "for" => FOR,
        "loop" => LOOP,
        "while" => WHILE,
        "continue" => CONTINUE,
        "break" => BREAK,
        "if" => IF,
        "else" => ELSE,
        "case" => CASE,
        "when" => WHEN,
        "return" => RETURN,
        "do" => DO,
        "end" => ENDSCOPE,
        "pub" => PUB,
        "self" => SELF,
        "fun" => FUN,
        "prc" => PRC,
        "lambda" => LAMBDA,
        "class" => CLASS,
        "super" => SUPER,
        "interface" => INTERFACE,
        "abstract" => ABSTRACT,
        "extends" => EXTENDS,
        "impl" => IMPL,
        "enum" => ENUM,
        "assert" => ASSERT,
        "debug" => DEBUG,
        "defer" => DEFER,
        "acyclic" => ACYCLIC,
        "unique" => UNIQUE,
        "as" => AS,
        "in" => IN,
        "and" => AND,
        "nand" => NAND,
        "or" => OR,
        "xor" => XOR,
        "nor" => NOR,
        "not" => NOT,
        "int" => INT,
        "long" => LONG,
        "float" => FLOAT,
        "double" => DOUBLE,
        "char" => CHAR,
        "string" => STRING,
        "bool" => BOOL,
        "true" => TRUE,
        "false" => FALSE,
        "." => DOT,
        ".." => RANGE,
        "yield" => YIELD,
        "sleep" => SLEEP,
        "tid" => TASKID,
        "EOF" => EOF
    }
    return keywords
end